[package]
name = "leeward"
version = "0.1.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
las = "0.7"
nalgebra = "0.23"
sbet = { git = "https://github.com/gadomski/sbet-rs" }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
utm = "0.1"

[dev-dependencies]
clap = "2.33"
csv = "1.1"