name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flags:
          - ""
          - "--all-features"
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test ${{ matrix.flags }}
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Fmt
        run: cargo fmt --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Clippy
        run: cargo clippy
  pdal:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          channels: conda-forge
      - uses: Swatinem/rust-cache@v2
      - name: Install PDAL
        run: conda install -y pdal
      - name: Build PDAL plugin
        run: scripts/build
      - name: Check PDAL drivers
        run: scripts/pdal --drivers | grep filters.leeward